env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: '@typescript-eslint/parser'
settings:
  import/resolver:
    node:
      extensions:
        - ".js"
        - ".jsx"
        - ".ts"
        - ".tsx"
      parserOptions:
  ecmaFeatures:
    jsx: true
    arrowFunctions: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/jsx-filename-extension:
    - 1
    - extensions:
        - ".js"
        - ".jsx"
        - ".ts"
        - ".tsx"
  react/jsx-props-no-spreading:
    - 1
    - custom: ignore
  jsx-a11y/anchor-is-valid: off
  react/no-danger: off
  global-require: off
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': error
  import/extensions:
    - error
    - never
    - ignorePackages: true
      ".css": always
      ".json": always

