env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
plugins:
  - react
  - import
  - jsx-a11y
  - '@typescript-eslint'
extends:
  - airbnb
  - airbnb-typescript
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - next
  - next/core-web-vitals
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - prettier
  - plugin:testing-library/react
  - plugin:jest-dom/recommended
parserOptions:
  project:
    - ./tsconfig.json
settings:
  react:
    version: detect
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  ecmaFeatures:
    jsx: true
    arrowFunctions: true
  ecmaVersion: 2020
  sourceType: module
rules:
  no-shadow: off
  '@typescript-eslint/no-shadow': error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
  max-len: off
  jsx-a11y/label-has-associated-control:
    - error
    - labelComponents:
        - label
      labelAttributes:
        - htmlFor
      controlComponents:
        - input
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  react/jsx-props-no-spreading:
    - 1
    - custom: ignore
  jsx-a11y/anchor-is-valid: off
  react/no-danger: off
  global-require: off
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': error
  import/extensions:
    - error
    - never
    - ignorePackages: true
      ".d.ts": never
      ".css": always
      ".json": always
